<h2>1. Load Libraries

In [1]:
import pandas as pd
import numpy as np

In [2]:
data_preprocess = pd.read_csv('Absenteeism_preprocessed.csv')
data_preprocess.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pet  Absenteeism Time in Hours  
0               30          0         2    1                          4  
1               31          0         1    0                          0  
2               31          0         0    0                          2  
3               24          0         2    0                          4  
4               30          0         2    1                          2

<h2>2. Logistic Regression is a type of classification, so classify people into two classes:
<h3>1) Moderately Absent(<=3 hours)        &        2) Excessively Absent(>=4 hours)


In [3]:
targets = np.where(data_preprocess['Absenteeism Time in Hours']>3,1,0)
targets

#np.where(condition,value if True, value if False)

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [4]:
data_preprocess['Excessive Absenteeism'] = targets
data_preprocess.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pet  Absenteeism Time in Hours  \
0               30          0         2    1                          4   
1               31          0         1    0                          0   
2               31          0         0    0                          2   
3               24          0         2    0                          4   
4               30          0         2    1                          2   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

In [5]:
targets.sum()/targets.shape[0]
# that is 46% of targets are = 1  & 54% are = 0

0.45571428571428574

In [6]:
# Backward Elimination
# drop ['Daily Work Load Average', 'Distance to Work', 'Day of the Week']
#the idea is that simplify our model by removing all features which have close to no contribution to the model
#For this, go back to the code and omit this code
#go to our last dataFrame manipulation state before we Standardized it

data_with_targets = data_preprocess.drop(['Absenteeism Time in Hours','Daily Work Load Average', 'Distance to Work', 'Day of the Week'],axis=1)
data_with_targets.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0         0         0         0         1            7   
1         0         0         0         0            7   
2         0         0         0         1            7   
3         1         0         0         0            7   
4         0         0         0         1            7   

   Transportation Expense  Age  Body Mass Index  Education  Children  Pet  \
0                     289   33               30          0         2    1   
1                     118   50               31          0         1    0   
2                     179   38               31          0         0    0   
3                     279   39               24          0         2    0   
4                     289   33               30          0         2    1   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

<h2>3. Select the inputs for Regression

In [7]:
unscaled_inputs = data_with_targets.iloc[:,:-1] 
#select and store all columns & rows but the last one
unscaled_inputs.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0         0         0         0         1            7   
1         0         0         0         0            7   
2         0         0         0         1            7   
3         1         0         0         0            7   
4         0         0         0         1            7   

   Transportation Expense  Age  Body Mass Index  Education  Children  Pet  
0                     289   33               30          0         2    1  
1                     118   50               31          0         1    0  
2                     179   38               31          0         0    0  
3                     279   39               24          0         2    0  
4                     289   33               30          0         2    1

<h2>4. Standardize the Data

In [8]:
from sklearn.preprocessing import StandardScaler

absenteeism_scaler = StandardScaler()

#Calculate mean & standard deviation of each feature from unscaled input
absenteeism_scaler.fit(unscaled_inputs)

#Transform the unscaled inputs using the information contained in absenteeism scaler
scaled_inputs = absenteeism_scaler.transform(unscaled_inputs)

scaled_inputs


array([[-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
         0.88046927,  0.26848661],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
        -0.01928035, -0.58968976],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
        -0.91902997, -0.58968976],
       ...,
       [ 1.73205081, -0.09298136, -0.31448545, ...,  2.23224237,
        -0.91902997, -0.58968976],
       [-0.57735027, -0.09298136, -0.31448545, ...,  2.23224237,
        -0.91902997, -0.58968976],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
        -0.01928035,  0.26848661]])

<h2>5. Split the Data into Train & Test 

In [9]:
from sklearn.model_selection import train_test_split
train_test_split(scaled_inputs,targets, shuffle = True)

x_train, x_test, y_train, y_test = train_test_split(scaled_inputs,targets, random_state=20, train_size = 0.8)
print(x_train.shape, y_train.shape)

# i.e input contains 560 observation along 14 variables, while targets are vector of length 560

(560, 11) (560,)


In [10]:
print(x_test.shape, y_test.shape)

(140, 11) (140,)


<h2>6. Modelling

In [11]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

<h3>6.1 Training the Model

In [12]:
reg = LogisticRegression()
reg.fit(x_train,y_train)

#Accuracy almost 80%. Our model learned to classify 80% of the observation correctly
reg.score(x_train,y_train)

0.7857142857142857

<h4>Manually check the accuracy

In [13]:
model_outputs = reg.predict(x_train)
model_outputs

array([0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,

In [14]:
model_outputs == y_train
#if there is a match, ans = True else False.

array([ True,  True, False,  True,  True,  True,  True,  True,  True,
        True, False,  True, False, False,  True,  True,  True,  True,
       False,  True, False,  True, False, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True, False,  True, False,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True, False,  True,  True, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,

In [15]:
np.sum((model_outputs == y_train))
#total number of correct predictions (True entities)

440

In [16]:
#Accuracy = correct prediction/ #observations

np.sum((model_outputs == y_train))/model_outputs.shape[0]

# manually accuracy = reg.score()  i.e almost 80%

0.7857142857142857

<h4> Finding intercept & coefficient

In [17]:
reg.intercept_

array([-0.21783203])

In [18]:
reg.coef_

array([[ 2.05335916,  0.3294394 ,  1.55190184,  1.29507765,  0.01972353,
         0.71354973, -0.20234414,  0.33178109, -0.13964122,  0.37829975,
        -0.31915632]])

In [19]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pet'], dtype=object)

In [20]:
feature_name = unscaled_inputs.columns.values

summary_table = pd.DataFrame(columns = ['Feature Name'], data = feature_name)

#add coefficient by taking transpose as by default nd-arrays are rows not columns 
summary_table['coefficient'] = np.transpose(reg.coef_)
summary_table


Feature Name  coefficient
0                 Reason_1     2.053359
1                 Reason_2     0.329439
2                 Reason_3     1.551902
3                 Reason_4     1.295078
4              Month Value     0.019724
5   Transportation Expense     0.713550
6                      Age    -0.202344
7          Body Mass Index     0.331781
8                Education    -0.139641
9                 Children     0.378300
10                     Pet    -0.319156

In [21]:
#add intercept
summary_table.index = summary_table.index + 1
#shift up all indices by 1. now, the 0th index is empty
summary_table.loc[0] = ['Intercept',reg.intercept_[0]]
summary_table = summary_table.sort_index()
summary_table

Feature Name  coefficient
0                Intercept    -0.217832
1                 Reason_1     2.053359
2                 Reason_2     0.329439
3                 Reason_3     1.551902
4                 Reason_4     1.295078
5              Month Value     0.019724
6   Transportation Expense     0.713550
7                      Age    -0.202344
8          Body Mass Index     0.331781
9                Education    -0.139641
10                Children     0.378300
11                     Pet    -0.319156

<h3>log(odd) = a0 = a1x1 +a2x2 + ............+ akxk
<h4>a = intercept/ bias , x = coef/ weight <br><br>
 # The closer the wt to 0, the smaller the wt<br>
 # whichever wt is bigger, its corresponding feature is <i>more important</i>

<h3> Interpreting the Coefficeint

In [22]:
summary_table['odds_ratio'] = np.exp(summary_table.coefficient)
summary_table

Feature Name  coefficient  odds_ratio
0                Intercept    -0.217832    0.804261
1                 Reason_1     2.053359    7.794039
2                 Reason_2     0.329439    1.390189
3                 Reason_3     1.551902    4.720439
4                 Reason_4     1.295078    3.651279
5              Month Value     0.019724    1.019919
6   Transportation Expense     0.713550    2.041224
7                      Age    -0.202344    0.816814
8          Body Mass Index     0.331781    1.393448
9                Education    -0.139641    0.869670
10                Children     0.378300    1.459800
11                     Pet    -0.319156    0.726762

In [23]:
summary_table.sort_values('odds_ratio',ascending=False)
#i.e most important weight on top and least important at last

Feature Name  coefficient  odds_ratio
1                 Reason_1     2.053359    7.794039
3                 Reason_3     1.551902    4.720439
4                 Reason_4     1.295078    3.651279
6   Transportation Expense     0.713550    2.041224
10                Children     0.378300    1.459800
8          Body Mass Index     0.331781    1.393448
2                 Reason_2     0.329439    1.390189
5              Month Value     0.019724    1.019919
9                Education    -0.139641    0.869670
7                      Age    -0.202344    0.816814
0                Intercept    -0.217832    0.804261
11                     Pet    -0.319156    0.726762

In [24]:
# A feature is not particularly important:
# if its coef is around 0 or if its odd ratio is around 1

# A weight(coef) of 0 implies that no matter the feature value, multiplying it by 0(in the model)

#drop [Daily Work Load Average, Distance to Work , Day of the Week] as the coef almost = 0 or 1

<h3>Testing the Model

In [25]:
reg.score(x_test, y_test)
#which is almost 73%. test accuracy is always less than train accuracy

0.7285714285714285

<h2>Save the Model

In [26]:
#pickle[module] : is a python module used to convert a python object into a character stream
#saving the model is equivalent saving the 'reg' object

import pickle
with open('model','wb') as file:
    pickle.dump(reg,file)

In [27]:
#save the absenteeism_scaler too
#by this we are separating the model from the training data
with open('scaler','wb') as file:
    pickle.dump(absenteeism_scaler,file)